[2024-05-23 13:15:45,647: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 13:15:45,648: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 13:15:45,648: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 13:15:45,648: INFO: common: created directory at: artifacts]
[2024-05-23 13:15:45,648: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 13:21:38,927: INFO: data_ingestion: artifacts/data_ingestion/RainTrainH.zip download! with following info: 
Date: Thu, 23 May 2024 17:15:44 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
Last-Modified: Tue, 05 Dec 2017 14:20:18 GMT
ETag: "45e0aef3-55f9888c78c80"
Accept-Ranges: bytes
Content-Length: 1172352755
Content-Type: application/zip
Connection: close

]
[2024-05-23 13:21:39,412: ERROR: main: HTTP Error 403: Forbidden]
Traceback (most recent call last):
  File "/Users/sushant/Desktop/WiperNet/main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 17, in main
    data_ingestion.download_file(data_ingestion_config.train_rain_L_URL, data_ingestion_config.local_train_L_path)
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/components/data_ingestion.py", line 18, in download_file
    filename, headers = request.urlretrieve(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
[2024-05-23 13:25:05,212: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 13:25:05,213: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 13:25:05,214: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 13:25:05,214: INFO: common: created directory at: artifacts]
[2024-05-23 13:25:05,214: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 13:25:05,693: ERROR: main: HTTP Error 403: Forbidden]
Traceback (most recent call last):
  File "/Users/sushant/Desktop/WiperNet/main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 17, in main
    data_ingestion.download_file(data_ingestion_config.train_rain_L_URL, data_ingestion_config.local_train_L_path)
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/components/data_ingestion.py", line 18, in download_file
    filename, headers = request.urlretrieve(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
[2024-05-23 13:25:24,358: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 13:25:24,359: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 13:25:24,359: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 13:25:24,359: INFO: common: created directory at: artifacts]
[2024-05-23 13:25:24,359: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 13:25:28,463: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-23 13:26:23,625: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 13:26:23,625: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 13:26:23,626: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 13:26:23,626: INFO: common: created directory at: artifacts]
[2024-05-23 13:26:23,626: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 13:26:27,739: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-23 13:26:55,091: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 13:26:55,091: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 13:26:55,092: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 13:26:55,092: INFO: common: created directory at: artifacts]
[2024-05-23 13:26:55,092: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 13:26:55,577: ERROR: main: HTTP Error 403: Forbidden]
Traceback (most recent call last):
  File "/Users/sushant/Desktop/WiperNet/main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 17, in main
    data_ingestion.download_file(data_ingestion_config.train_rain_L_URL, data_ingestion_config.local_train_L_path)
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/components/data_ingestion.py", line 18, in download_file
    filename, headers = request.urlretrieve(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
[2024-05-23 13:29:22,820: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 13:29:22,821: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 13:29:22,821: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 13:29:22,821: INFO: common: created directory at: artifacts]
[2024-05-23 13:29:22,821: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 13:29:23,315: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-23 15:39:42,650: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 15:39:42,651: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 15:39:42,651: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 15:39:42,651: INFO: common: created directory at: artifacts]
[2024-05-23 15:39:42,651: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 15:39:42,651: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-23 15:40:19,141: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 15:40:19,141: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 15:40:19,142: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 15:40:19,142: INFO: common: created directory at: artifacts]
[2024-05-23 15:40:19,142: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 15:40:19,142: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-23 15:41:38,227: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 15:41:38,229: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 15:41:38,231: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 15:41:38,231: INFO: common: created directory at: artifacts]
[2024-05-23 15:41:38,232: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 15:41:38,232: ERROR: main: 'str' object has no attribute 'iterdir']
Traceback (most recent call last):
  File "/Users/sushant/Desktop/WiperNet/main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 20, in main
    data_ingestion.combine_directories()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/components/data_ingestion.py", line 43, in combine_directories
    for sub_dir in self.config.train_dir.iterdir():
AttributeError: 'str' object has no attribute 'iterdir'
[2024-05-23 15:42:49,757: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 15:42:49,758: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 15:42:49,758: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 15:42:49,759: INFO: common: created directory at: artifacts]
[2024-05-23 15:42:49,760: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 15:42:49,760: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-23 15:43:34,904: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 15:43:34,905: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 15:43:34,905: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 15:43:34,905: INFO: common: created directory at: artifacts]
[2024-05-23 15:43:34,905: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 15:43:34,910: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-23 16:53:58,913: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 16:53:58,915: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 16:53:58,915: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 16:53:58,915: INFO: common: created directory at: artifacts]
[2024-05-23 16:53:58,915: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 16:53:58,920: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-23 17:01:49,901: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 17:01:49,902: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 17:01:49,903: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 17:01:49,903: INFO: common: created directory at: artifacts]
[2024-05-23 17:01:49,903: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 17:01:49,975: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-23 17:04:44,030: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 17:04:44,031: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 17:04:44,031: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 17:04:44,031: INFO: common: created directory at: artifacts]
[2024-05-23 17:04:44,031: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 17:04:46,301: INFO: data_ingestion: Processed 2000 ground truth images and 2000 degraded images.]
[2024-05-23 17:04:46,301: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-23 17:20:00,614: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 17:20:00,615: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 17:20:00,615: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 17:20:00,615: INFO: common: created directory at: artifacts]
[2024-05-23 17:20:00,615: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 17:20:00,690: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-23 17:21:55,131: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 17:21:55,131: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 17:21:55,132: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 17:21:55,132: INFO: common: created directory at: artifacts]
[2024-05-23 17:21:55,132: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 17:21:55,182: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-23 17:24:28,169: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 17:24:28,169: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 17:24:28,170: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 17:24:28,170: INFO: common: created directory at: artifacts]
[2024-05-23 17:24:28,170: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 17:24:28,217: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-23 17:26:01,861: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-23 17:26:01,862: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-23 17:26:01,862: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-23 17:26:01,862: INFO: common: created directory at: artifacts]
[2024-05-23 17:26:01,862: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-23 17:26:04,020: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 11:48:16,240: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 11:48:16,241: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 11:48:16,241: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 11:48:16,242: INFO: common: created directory at: artifacts]
[2024-05-24 11:48:16,242: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 11:48:16,412: ERROR: main: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} artifacts/train/ground-truth_47.png; No such file or directory
	 [[{{node ReadFile_1}}]] [Op:IteratorGetNext] name: ]
Traceback (most recent call last):
  File "/Users/sushant/Desktop/WiperNet/main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 27, in main
    preprocessor.save_preprocessed_images('artifacts/preprocessed')
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/components/data_preprocessing.py", line 76, in save_preprocessed_images
    for input_image, real_image in self.train_dataset.take(1):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 810, in __next__
    return self._next_internal()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 773, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3029, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 5883, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} artifacts/train/ground-truth_47.png; No such file or directory
	 [[{{node ReadFile_1}}]] [Op:IteratorGetNext] name: 
[2024-05-24 11:50:39,286: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 11:50:39,287: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 11:50:39,288: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 11:50:39,288: INFO: common: created directory at: artifacts]
[2024-05-24 11:50:39,288: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 11:50:39,549: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 11:50:39,936: ERROR: main: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} artifacts/train/ground-truth_1017.png; No such file or directory
	 [[{{node ReadFile_1}}]] [Op:IteratorGetNext] name: ]
Traceback (most recent call last):
  File "/Users/sushant/Desktop/WiperNet/main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 27, in main
    preprocessor.save_preprocessed_images('artifacts/preprocessed')
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/components/data_preprocessing.py", line 77, in save_preprocessed_images
    for input_image, real_image in self.train_dataset.take(1):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 810, in __next__
    return self._next_internal()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 773, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3029, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 5883, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} artifacts/train/ground-truth_1017.png; No such file or directory
	 [[{{node ReadFile_1}}]] [Op:IteratorGetNext] name: 
[2024-05-24 11:51:17,632: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 11:51:17,633: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 11:51:17,633: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 11:51:17,633: INFO: common: created directory at: artifacts]
[2024-05-24 11:51:17,633: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 11:51:17,633: ERROR: main: 'DataPreProcessing' object has no attribute 'data_ingestion_config']
Traceback (most recent call last):
  File "/Users/sushant/Desktop/WiperNet/main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 25, in main
    preprocessor = DataPreProcessing(data_ingestion_config, config)
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/components/data_preprocessing.py", line 10, in __init__
    logger.info(self.data_ingestion_config.train_dir)
AttributeError: 'DataPreProcessing' object has no attribute 'data_ingestion_config'
[2024-05-24 11:51:58,818: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 11:51:58,819: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 11:51:58,820: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 11:51:58,820: INFO: common: created directory at: artifacts]
[2024-05-24 11:51:58,820: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 11:51:59,085: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 11:51:59,475: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 11:52:38,018: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 11:52:38,019: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 11:52:38,020: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 11:52:38,020: INFO: common: created directory at: artifacts]
[2024-05-24 11:52:38,020: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 11:52:38,282: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 11:52:38,669: ERROR: main: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} artifacts/train/ground-truth_1530.png; No such file or directory
	 [[{{node ReadFile_1}}]] [Op:IteratorGetNext] name: ]
Traceback (most recent call last):
  File "/Users/sushant/Desktop/WiperNet/main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 27, in main
    preprocessor.save_preprocessed_images('artifacts/preprocessed')
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/components/data_preprocessing.py", line 77, in save_preprocessed_images
    for input_image, real_image in self.train_dataset.take(1):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 810, in __next__
    return self._next_internal()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 773, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3029, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 5883, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} artifacts/train/ground-truth_1530.png; No such file or directory
	 [[{{node ReadFile_1}}]] [Op:IteratorGetNext] name: 
[2024-05-24 11:53:16,565: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 11:53:16,566: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 11:53:16,566: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 11:53:16,566: INFO: common: created directory at: artifacts]
[2024-05-24 11:53:16,566: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 11:53:16,821: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 11:53:17,212: ERROR: main: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} artifacts/train/ground-truth_665.png; No such file or directory
	 [[{{node ReadFile_1}}]] [Op:IteratorGetNext] name: ]
Traceback (most recent call last):
  File "/Users/sushant/Desktop/WiperNet/main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 27, in main
    preprocessor.save_preprocessed_images('artifacts/preprocessed')
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/components/data_preprocessing.py", line 77, in save_preprocessed_images
    for input_image, real_image in self.train_dataset.take(1):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 810, in __next__
    return self._next_internal()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 773, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3029, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 5883, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} artifacts/train/ground-truth_665.png; No such file or directory
	 [[{{node ReadFile_1}}]] [Op:IteratorGetNext] name: 
[2024-05-24 11:53:45,564: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 11:53:45,565: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 11:53:45,565: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 11:53:45,565: INFO: common: created directory at: artifacts]
[2024-05-24 11:53:45,565: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 11:53:45,817: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 11:53:46,227: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 11:55:03,268: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 11:55:03,269: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 11:55:03,270: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 11:55:03,270: INFO: common: created directory at: artifacts]
[2024-05-24 11:55:03,270: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 11:55:03,514: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 11:55:03,843: ERROR: main: too many values to unpack (expected 2)]
Traceback (most recent call last):
  File "/Users/sushant/Desktop/WiperNet/main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 27, in main
    preprocessor.save_preprocessed_images('artifacts/preprocessed')
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/components/data_preprocessing.py", line 77, in save_preprocessed_images
    for input_image, real_image in self.train_dataset.take(1):
ValueError: too many values to unpack (expected 2)
[2024-05-24 11:55:49,778: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 11:55:49,779: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 11:55:49,779: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 11:55:49,779: INFO: common: created directory at: artifacts]
[2024-05-24 11:55:49,779: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 11:55:50,035: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 11:55:50,356: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 11:55:50,365: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 11:59:30,456: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 11:59:30,456: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 11:59:30,457: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 11:59:30,457: INFO: common: created directory at: artifacts]
[2024-05-24 11:59:30,457: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 11:59:30,501: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 12:00:35,100: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:00:35,101: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:00:35,102: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:00:35,102: INFO: common: created directory at: artifacts]
[2024-05-24 12:00:35,102: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:00:35,239: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 12:01:59,800: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:01:59,801: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:01:59,802: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:01:59,802: INFO: common: created directory at: artifacts]
[2024-05-24 12:01:59,802: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:01:59,955: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 12:03:57,996: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:03:57,997: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:03:57,998: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:03:57,998: INFO: common: created directory at: artifacts]
[2024-05-24 12:03:57,998: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:03:58,276: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:03:58,584: INFO: api: Tensor("StaticRegexReplace:0", shape=(), dtype=string)]
[2024-05-24 12:03:58,609: ERROR: main: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} ./artifacts/train/ground-truth_1225.png; No such file or directory
	 [[{{node ReadFile_1}}]] [Op:IteratorGetNext] name: ]
Traceback (most recent call last):
  File "/Users/sushant/Desktop/WiperNet/main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 62, in main
    for file in train_dataset:  # Print the first 10 file paths
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 810, in __next__
    return self._next_internal()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 773, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3029, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 5883, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} ./artifacts/train/ground-truth_1225.png; No such file or directory
	 [[{{node ReadFile_1}}]] [Op:IteratorGetNext] name: 
[2024-05-24 12:04:35,603: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:04:35,604: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:04:35,605: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:04:35,605: INFO: common: created directory at: artifacts]
[2024-05-24 12:04:35,605: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:04:35,876: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:04:36,205: ERROR: main: 'numpy.ndarray' object has no attribute 'decode']
Traceback (most recent call last):
  File "/Users/sushant/Desktop/WiperNet/main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 64, in main
    print(file.numpy().decode('utf-8'))
AttributeError: 'numpy.ndarray' object has no attribute 'decode'
[2024-05-24 12:04:51,171: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:04:51,172: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:04:51,172: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:04:51,173: INFO: common: created directory at: artifacts]
[2024-05-24 12:04:51,173: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:04:51,438: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:04:52,479: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 12:05:10,093: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:05:10,094: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:05:10,094: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:05:10,094: INFO: common: created directory at: artifacts]
[2024-05-24 12:05:10,094: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:05:10,866: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 12:05:30,264: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:05:30,265: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:05:30,265: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:05:30,265: INFO: common: created directory at: artifacts]
[2024-05-24 12:05:30,265: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:05:31,044: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 12:06:19,864: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:06:19,865: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:06:19,866: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:06:19,866: INFO: common: created directory at: artifacts]
[2024-05-24 12:06:19,866: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:06:20,634: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 12:06:51,582: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:06:51,583: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:06:51,584: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:06:51,584: INFO: common: created directory at: artifacts]
[2024-05-24 12:06:51,584: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:06:52,349: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 12:07:26,700: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:07:26,701: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:07:26,702: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:07:26,702: INFO: common: created directory at: artifacts]
[2024-05-24 12:07:26,702: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:07:26,793: ERROR: main: in user code:

    File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 26, in load_image_train  *
        print(real_image_path.numpy().decode('utf-8'))

    AttributeError: 'SymbolicTensor' object has no attribute 'numpy'
]
Traceback (most recent call last):
  File "/Users/sushant/Desktop/WiperNet/main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 59, in main
    train_dataset = train_dataset.map(load_image_train, num_parallel_calls=tf.data.AUTOTUNE)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2280, in map
    return map_op._map_v2(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/data/ops/map_op.py", line 40, in _map_v2
    return _ParallelMapDataset(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/data/ops/map_op.py", line 148, in __init__
    self._map_func = structured_function.StructuredFunctionWrapper(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/data/ops/structured_function.py", line 265, in __init__
    self._function = fn_factory()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 1227, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 1197, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 695, in _initialize
    self._concrete_variable_creation_fn = tracing_compilation.trace_function(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py", line 178, in trace_function
    concrete_function = _maybe_define_function(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py", line 283, in _maybe_define_function
    concrete_function = _create_concrete_function(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py", line 310, in _create_concrete_function
    traced_func_graph = func_graph_module.func_graph_from_py_func(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py", line 1059, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 598, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/data/ops/structured_function.py", line 231, in wrapped_fn
    ret = wrapper_helper(*args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/data/ops/structured_function.py", line 161, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 693, in wrapper
    raise e.ag_error_metadata.to_exception(e)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 690, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/var/folders/1l/h5xg37d142b485g8nrk47d8m0000gn/T/__autograph_generated_filenrit46o9.py", line 12, in tf__load_image_train
    ag__.ld(print)(ag__.converted_call(ag__.converted_call(ag__.ld(real_image_path).numpy, (), None, fscope).decode, ('utf-8',), None, fscope))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/tensorflow/python/framework/tensor.py", line 261, in __getattr__
    self.__getattribute__(name)
AttributeError: in user code:

    File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 26, in load_image_train  *
        print(real_image_path.numpy().decode('utf-8'))

    AttributeError: 'SymbolicTensor' object has no attribute 'numpy'

[2024-05-24 12:08:40,938: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:08:40,939: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:08:40,939: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:08:40,939: INFO: common: created directory at: artifacts]
[2024-05-24 12:08:40,939: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:08:41,729: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 12:12:15,012: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:12:15,013: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:12:15,013: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:12:15,013: INFO: common: created directory at: artifacts]
[2024-05-24 12:12:15,013: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:12:15,278: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:12:15,608: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:12:15,617: INFO: api: Tensor("StaticRegexReplace:0", shape=(), dtype=string)]
[2024-05-24 12:12:15,675: ERROR: main: "'ConfigBox' object has no attribute 'batch_size'"]
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/box/box.py", line 592, in __getitem__
    return super().__getitem__(item)
KeyError: 'BATCH_SIZE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/box/box.py", line 631, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/box/box.py", line 619, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'BATCH_SIZE'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/box/box.py", line 633, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'ConfigBox' object has no attribute 'BATCH_SIZE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/box/config_box.py", line 29, in __getattr__
    return super().__getattr__(item)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/box/box.py", line 647, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'BATCH_SIZE'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/box/box.py", line 592, in __getitem__
    return super().__getitem__(item)
KeyError: 'batch_size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/box/box.py", line 631, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/box/box.py", line 619, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'batch_size'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/box/box.py", line 633, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'ConfigBox' object has no attribute 'batch_size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sushant/Desktop/WiperNet/main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 24, in main
    preprocessor.preprocess()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/components/data_preprocessing.py", line 45, in preprocess
    self.train_dataset = self.train_dataset.batch(self.config.params.BATCH_SIZE)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/box/config_box.py", line 31, in __getattr__
    return super().__getattr__(item.lower())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/site-packages/box/box.py", line 647, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'batch_size'"
[2024-05-24 12:12:43,099: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:12:43,100: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:12:43,100: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:12:43,101: INFO: common: created directory at: artifacts]
[2024-05-24 12:12:43,101: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:12:43,369: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:12:43,689: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:12:43,697: INFO: api: Tensor("StaticRegexReplace:0", shape=(), dtype=string)]
[2024-05-24 12:12:43,813: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 12:13:25,723: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:13:25,724: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:13:25,724: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:13:25,724: INFO: common: created directory at: artifacts]
[2024-05-24 12:13:25,724: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:13:25,997: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:13:26,319: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:13:26,327: INFO: api: Tensor("StaticRegexReplace:0", shape=(), dtype=string)]
[2024-05-24 12:13:26,654: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 12:13:40,037: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:13:40,038: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:13:40,038: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:13:40,038: INFO: common: created directory at: artifacts]
[2024-05-24 12:13:40,038: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:13:40,306: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:13:40,625: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:13:40,633: INFO: api: Tensor("StaticRegexReplace:0", shape=(), dtype=string)]
[2024-05-24 12:13:43,014: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 12:14:23,563: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:14:23,564: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:14:23,564: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:14:23,564: INFO: common: created directory at: artifacts]
[2024-05-24 12:14:23,564: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:14:23,833: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:14:24,161: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:14:24,170: INFO: api: Tensor("StaticRegexReplace:0", shape=(), dtype=string)]
[2024-05-24 12:14:24,491: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 12:14:35,730: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:14:35,731: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:14:35,731: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:14:35,732: INFO: common: created directory at: artifacts]
[2024-05-24 12:14:35,732: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:14:35,999: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:14:36,320: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:14:36,329: INFO: api: Tensor("StaticRegexReplace:0", shape=(), dtype=string)]
[2024-05-24 12:14:36,662: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 12:15:18,706: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-24 12:15:18,707: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 12:15:18,708: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 12:15:18,708: INFO: common: created directory at: artifacts]
[2024-05-24 12:15:18,708: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 12:15:18,971: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:15:19,293: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 12:15:19,301: INFO: api: Tensor("StaticRegexReplace:0", shape=(), dtype=string)]
[2024-05-24 12:16:10,156: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-24 13:15:55,600: INFO: main: >>>>>> stage Data ingestion stage started <<<<<<]
[2024-05-24 13:15:55,602: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 13:15:55,602: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 13:15:55,602: INFO: common: created directory at: artifacts]
[2024-05-24 13:15:55,602: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 13:15:55,602: INFO: main: >>>>>> stage Data ingestion stage completed <<<<<<

x==========x]
[2024-05-24 13:15:55,602: INFO: main: >>>>>> stage Data pre-processing stage started <<<<<<]
[2024-05-24 13:15:55,603: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 13:15:55,603: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 13:15:55,603: INFO: common: created directory at: artifacts]
[2024-05-24 13:15:55,603: ERROR: main: DataIngestionConfig.__init__() got an unexpected keyword argument 'output_dir']
Traceback (most recent call last):
  File "/Users/sushant/Desktop/WiperNet/main.py", line 20, in <module>
    preprocessor.main()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_02_data_preprocessing.py", line 15, in main
    data_preprocessing_config = config.get_data_preprocessing_config()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/config/configuration.py", line 40, in get_data_preprocessing_config
    data_ingestion_config = DataIngestionConfig(
TypeError: DataIngestionConfig.__init__() got an unexpected keyword argument 'output_dir'
[2024-05-24 13:16:56,214: INFO: main: >>>>>> stage Data ingestion stage started <<<<<<]
[2024-05-24 13:16:56,215: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 13:16:56,216: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 13:16:56,216: INFO: common: created directory at: artifacts]
[2024-05-24 13:16:56,216: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-24 13:16:56,216: INFO: main: >>>>>> stage Data ingestion stage completed <<<<<<

x==========x]
[2024-05-24 13:16:56,216: INFO: main: >>>>>> stage Data pre-processing stage started <<<<<<]
[2024-05-24 13:16:56,216: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-24 13:16:56,217: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-24 13:16:56,217: INFO: common: created directory at: artifacts]
[2024-05-24 13:16:56,479: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 13:16:56,788: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-24 13:16:56,796: INFO: api: Tensor("StaticRegexReplace:0", shape=(), dtype=string)]
[2024-05-24 13:17:46,259: INFO: main: >>>>>> stage Data pre-processing stage completed <<<<<<

x==========x]
[2024-05-26 12:45:13,624: INFO: font_manager: Failed to extract font properties from /System/Library/Fonts/Supplemental/NISC18030.ttf: In FT2Font: Could not set the fontsize (invalid pixel size; error code 0x17)]
[2024-05-26 12:45:13,666: INFO: font_manager: Failed to extract font properties from /System/Library/Fonts/Apple Color Emoji.ttc: In FT2Font: Could not set the fontsize (invalid pixel size; error code 0x17)]
[2024-05-26 12:45:13,775: INFO: font_manager: Failed to extract font properties from /System/Library/Fonts/LastResort.otf: tuple indices must be integers or slices, not str]
[2024-05-26 12:45:13,827: INFO: font_manager: generated new fontManager]
[2024-05-26 12:45:14,379: INFO: main: >>>>>> stage Data ingestion stage started <<<<<<]
[2024-05-26 12:45:14,381: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-26 12:45:14,381: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-26 12:45:14,381: INFO: common: created directory at: artifacts]
[2024-05-26 12:45:14,381: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-26 12:45:14,382: INFO: main: >>>>>> stage Data ingestion stage completed <<<<<<

x==========x]
[2024-05-26 12:45:14,382: INFO: main: >>>>>> stage Data pre-processing stage started <<<<<<]
[2024-05-26 12:45:14,382: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-26 12:45:14,383: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-26 12:45:14,383: INFO: common: created directory at: artifacts]
[2024-05-26 12:45:14,656: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-26 12:45:14,934: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-26 12:45:14,942: INFO: api: Tensor("StaticRegexReplace:0", shape=(), dtype=string)]
[2024-05-26 12:45:15,840: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.]
[2024-05-26 12:45:15,842: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.]
[2024-05-26 13:14:39,998: INFO: main: >>>>>> stage Data ingestion stage started <<<<<<]
[2024-05-26 13:14:39,999: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-26 13:14:40,000: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-26 13:14:40,000: INFO: common: created directory at: artifacts]
[2024-05-26 13:14:40,000: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-26 13:14:40,000: INFO: main: >>>>>> stage Data ingestion stage completed <<<<<<

x==========x]
[2024-05-26 13:14:40,000: INFO: main: >>>>>> stage Data pre-processing stage started <<<<<<]
[2024-05-26 13:14:40,001: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-26 13:14:40,001: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-26 13:14:40,001: INFO: common: created directory at: artifacts]
[2024-05-26 13:14:40,282: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-26 13:14:40,574: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-26 13:14:40,583: INFO: api: Tensor("StaticRegexReplace:0", shape=(), dtype=string)]
[2024-05-26 13:14:41,489: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.]
[2024-05-26 13:14:41,491: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.]
[2024-05-26 13:17:12,680: INFO: main: >>>>>> stage Data ingestion stage started <<<<<<]
[2024-05-26 13:17:12,681: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-26 13:17:12,682: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-26 13:17:12,682: INFO: common: created directory at: artifacts]
[2024-05-26 13:17:12,682: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-26 13:17:12,682: INFO: main: >>>>>> stage Data ingestion stage completed <<<<<<

x==========x]
[2024-05-26 13:17:12,682: INFO: main: >>>>>> stage Data pre-processing stage started <<<<<<]
[2024-05-26 13:17:12,683: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-26 13:17:12,683: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-26 13:17:12,683: INFO: common: created directory at: artifacts]
[2024-05-26 13:17:12,952: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-26 13:17:13,238: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-26 13:17:13,246: INFO: api: Tensor("StaticRegexReplace:0", shape=(), dtype=string)]
[2024-05-26 13:19:21,185: INFO: main: >>>>>> stage Data ingestion stage started <<<<<<]
[2024-05-26 13:19:21,186: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-26 13:19:21,187: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-26 13:19:21,187: INFO: common: created directory at: artifacts]
[2024-05-26 13:19:21,187: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-26 13:19:21,187: INFO: main: >>>>>> stage Data ingestion stage completed <<<<<<

x==========x]
[2024-05-26 13:19:21,187: INFO: main: >>>>>> stage Data pre-processing stage started <<<<<<]
[2024-05-26 13:19:21,188: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-26 13:19:21,188: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-26 13:19:21,188: INFO: common: created directory at: artifacts]
[2024-05-26 13:19:21,461: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-26 13:19:21,749: INFO: api: Tensor("args_0:0", shape=(), dtype=string)]
[2024-05-26 13:19:21,758: INFO: api: Tensor("StaticRegexReplace:0", shape=(), dtype=string)]
[2024-05-26 13:19:22,719: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.]
[2024-05-26 13:19:22,721: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.]
[2024-05-27 12:43:00,932: INFO: main: >>>>>> stage Data ingestion stage started <<<<<<]
[2024-05-27 12:43:00,934: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-27 12:43:00,934: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 12:43:00,935: INFO: common: created directory at: artifacts]
[2024-05-27 12:43:00,935: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-27 12:43:04,717: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion_test/RainH.zip']
Traceback (most recent call last):
  File "/Users/sushant/Desktop/WiperNet/main.py", line 10, in <module>
    data_ingestion.main()
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/pipeline/stage_01_data_ingestion.py", line 18, in main
    data_ingestion.download_file(data_ingestion_config.test_rain_H_URL, data_ingestion_config.local_test_H_path)
  File "/Users/sushant/Desktop/WiperNet/src/wipernet/components/data_ingestion.py", line 20, in download_file
    filename, headers = request.urlretrieve(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/shetty/lib/python3.10/urllib/request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion_test/RainH.zip'
[2024-05-27 12:44:49,670: INFO: main: >>>>>> stage Data ingestion stage started <<<<<<]
[2024-05-27 12:44:49,672: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-27 12:44:49,673: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 12:44:49,673: INFO: common: created directory at: artifacts]
[2024-05-27 12:44:49,673: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-27 12:44:49,673: INFO: common: created directory at: artifacts/data_ingestion_test/]
[2024-05-27 12:47:41,677: INFO: data_ingestion: artifacts/data_ingestion_test/RainH.zip download! with following info: 
Date: Mon, 27 May 2024 16:44:47 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
Last-Modified: Tue, 05 Dec 2017 14:17:12 GMT
ETag: "3c91367-55f987db16a00"
Accept-Ranges: bytes
Content-Length: 63509351
Content-Type: application/zip
Connection: close

]
[2024-05-27 12:48:26,723: INFO: data_ingestion: artifacts/data_ingestion_test/RainL.zip download! with following info: 
Date: Mon, 27 May 2024 16:47:39 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
Last-Modified: Tue, 05 Dec 2017 14:17:18 GMT
ETag: "37c9d7e-55f987e0cf780"
Accept-Ranges: bytes
Content-Length: 58498430
Content-Type: application/zip
Connection: close

]
[2024-05-27 12:48:27,187: INFO: main: >>>>>> stage Data ingestion stage completed <<<<<<

x==========x]
[2024-05-27 12:55:46,473: INFO: main: >>>>>> stage Data ingestion stage started <<<<<<]
[2024-05-27 12:55:46,475: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-05-27 12:55:46,475: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 12:55:46,475: INFO: common: created directory at: artifacts]
[2024-05-27 12:55:46,475: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-27 12:55:46,475: INFO: common: created directory at: artifacts/data_ingestion_test/]
[2024-05-27 12:55:46,702: INFO: data_ingestion: Processed 200 ground truth images and 200 degraded images.]
[2024-05-27 12:55:46,702: INFO: main: >>>>>> stage Data ingestion stage completed <<<<<<

x==========x]
